@Library('shared-library@main') _
pipeline {
    agent any

    stages {
      
        stage('deploy') {
            steps {
              script{
                    def config=[namespace:"app2",yaml:"k8s/app2.yaml"]
                    deployApp(config)
            }
        }
    }

    post {
        success {
            echo 'app2 deploy completato con successo'
        }
        failure {
            echo 'Errore nel deploy app2'
        }
    }
}
